title: Jason Kendrick Pape's Portfolio
description: > # this means to ignore newlines until "baseurl:"
  A portfolio containing samples of work in web development, Photoshop, web animation, and game design
permalink: ':title/'
baseurl: "/jekyll-portfolio" # the subpath of your site, e.g. /blog
url: "https://jasonkpape.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Jason Kendrick Pape # add your name
author-img: capybara-128w-128h.jpg # add your photo
about-author: I am a computer programming student interested game design and other software development.
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: jasonkpape # add your Github handle
social-linkedin: jason-pape-7635798a # add your Linkedin handle
social-email: jason.k.pape@gmail.com # add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
